# Generated by Django 5.2.8 on 2025-11-09 23:04

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpertIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=150, unique=True)),
                ('definition', wagtail.fields.RichTextField()),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., en, fr, pt', max_length=10, unique=True)),
                ('name', models.CharField(help_text='e.g., English', max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('iso', models.CharField(blank=True, help_text='Optional short code (e.g., KE, EAC, SSA)', max_length=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestimonialIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebinarIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('kind', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('tool', 'Tool / App'), ('template', 'Template'), ('link', 'External Link'), ('dataset', 'Dataset')], max_length=20)),
                ('date', models.DateField(help_text='Resource date (publish/issue).')),
                ('featured', models.BooleanField(default=False)),
                ('abstract', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('notes', 0), ('document', 1), ('external_link', 2), ('embed', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'hr']}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Inline extra document (optional)'}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Inline extra URL (optional)'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Embed video or webpage'})})),
                ('audiences', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='resources', to='portal.audience')),
                ('languages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='resources', to='portal.language')),
                ('regions', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='resources', to='portal.region')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Card image / preview thumbnail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, help_text='Optional display name', max_length=200)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portal.resourcepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, help_text='Optional display name', max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portal.resourcepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='portal.resourcepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='portal.ResourceTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='resources', to='portal.topic'),
        ),
        migrations.CreateModel(
            name='ExpertPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('languages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='experts', to='portal.language')),
                ('regions', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='experts', to='portal.region')),
                ('expertise', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='experts', to='portal.topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='WebinarPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_datetime', models.DateTimeField()),
                ('platform', models.CharField(blank=True, max_length=80)),
                ('registration_url', models.URLField(blank=True)),
                ('recording', wagtail.fields.StreamField([], blank=True, block_lookup={})),
                ('materials', wagtail.fields.StreamField([('slides', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})})),
                ('languages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='webinars', to='portal.language')),
                ('speakers', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='talks', to='portal.expertpage')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='webinars', to='portal.topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='TestimonialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author', models.CharField(max_length=150)),
                ('org', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('quote', models.TextField()),
                ('about_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portal.resourcepage')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='testimonials', to='portal.topic')),
                ('about_webinar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portal.webinarpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', modelsearch.index.Indexed),
        ),
    ]
