# Generated by Django 5.2.8 on 2025-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_seed_taxonomies'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='learning_order',
            field=models.PositiveIntegerField(blank=True, help_text='Optional sequence number for learning journey (1 = first).', null=True),
        ),
    ]
