# Generated by Django 5.2.8 on 2025-12-13 17:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_resourcepage_learning_order'),
        ('wagtailmedia', '0005_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialpage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='body',
            field=wagtail.fields.StreamField([('notes', 0), ('document', 1), ('external_link', 2), ('embed', 3), ('video', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'hr']}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Inline extra document (optional)'}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Inline extra URL (optional)'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Embed video or webpage'}), 4: ('wagtailmedia.blocks.VideoChooserBlock', (), {'help_text': 'Inline video (optional)'})}),
        ),
        migrations.AlterField(
            model_name='webinarpage',
            name='recording',
            field=wagtail.fields.StreamField([('video', 0)], blank=True, block_lookup={0: ('wagtailmedia.blocks.VideoChooserBlock', (), {})}),
        ),
    ]
