# Generated by Django 5.2.8 on 2025-12-13 18:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_resourcepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepage',
            name='body',
            field=wagtail.fields.StreamField([('notes', 0), ('document', 1), ('external_link', 2), ('embed', 3), ('office_viewer', 5), ('pdf_viewer', 7), ('video', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'hr']}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Inline extra document (optional)'}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Inline extra URL (optional)'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Embed video or webpage'}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('document', 4)]], {'help_text': 'Preview Word, PowerPoint, Excel inline'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload a PDF document', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('document', 6)]], {'help_text': 'Preview pdf'}), 8: ('wagtailmedia.blocks.VideoChooserBlock', (), {'help_text': 'Inline video (optional)'})}),
        ),
    ]
