# Generated by Django 5.2.8 on 2026-02-25 06:35

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_resourcepage_body'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TrainingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.TextField(blank=True, help_text='Short summary shown on cards and hero sections.')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open for registration'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('self_paced', 'Self-paced')], default='upcoming', max_length=20)),
                ('delivery_format', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person'), ('hybrid', 'Hybrid'), ('self_paced', 'Self-paced'), ('cohort', 'Cohort-based')], default='online', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, help_text='e.g. 2 hours, 3 days, 6 weeks', max_length=80)),
                ('venue', models.CharField(blank=True, help_text='Physical venue or city (for in-person/hybrid).', max_length=255)),
                ('platform', models.CharField(blank=True, help_text='Zoom, Teams, Moodle, etc.', max_length=120)),
                ('application_url', models.URLField(blank=True, help_text='Registration / application link.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('certificate_available', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('overview', wagtail.fields.RichTextField(blank=True)),
                ('learning_outcomes', wagtail.fields.RichTextField(blank=True, help_text='What participants will learn.')),
                ('who_should_join', wagtail.fields.RichTextField(blank=True, help_text='Intended audience / participant profile.')),
                ('curriculum_notes', wagtail.fields.RichTextField(blank=True, help_text='Optional extra curriculum description.')),
                ('faq', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('notes', 0), ('document', 1), ('external_link', 2), ('embed', 3), ('office_viewer', 5), ('pdf_viewer', 7), ('video', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link', 'hr']}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Inline training document (optional)'}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Inline external URL (optional)'}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Embed video or webpage'}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('document', 4)]], {'help_text': 'Preview Word, PowerPoint, Excel inline'}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload a PDF document', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('document', 6)]], {'help_text': 'Preview PDF inline'}), 8: ('wagtailmedia.blocks.VideoChooserBlock', (), {'help_text': 'Inline video (optional)'})})),
                ('audiences', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='trainings', to='portal.audience')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Optional cover image for cards and page header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('languages', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='trainings', to='portal.language')),
                ('regions', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='trainings', to='portal.region')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='trainings', to='portal.topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('duration_text', models.CharField(blank=True, help_text='e.g. 45 min, 1 week', max_length=60)),
                ('resource', models.ForeignKey(blank=True, help_text='Optional linked resource from the repository.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_modules', to='portal.resourcepage')),
                ('webinar', models.ForeignKey(blank=True, help_text='Optional linked webinar/recording.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_modules', to='portal.webinarpage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='portal.trainingpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingRelatedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_resources', to='portal.trainingpage')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_trainings', to='portal.resourcepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingRelatedWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_webinars', to='portal.trainingpage')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_trainings', to='portal.webinarpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, help_text='Optional role label (e.g., Lead facilitator, Guest speaker).', max_length=120)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_roles', to='portal.expertpage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='portal.trainingpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
