# Generated by Django 5.2.8 on 2026-02-25 12:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_trainingindexpage_trainingpage_trainingmodule_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Partners', max_length=120)),
                ('slug', models.SlugField(help_text='Unique key for reuse (e.g. core-partners, training-partners)', max_length=120, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Optional helper text shown below title', max_length=255)),
                ('style_variant', models.CharField(choices=[('default', 'Default'), ('soft', 'Soft'), ('compact', 'Compact')], default='default', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('partner_type', models.CharField(blank=True, help_text='e.g. Donor, Implementing Partner, Knowledge Partner', max_length=60)),
                ('logo', models.ForeignKey(blank=True, help_text='Preferred: transparent PNG/WebP logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_row',
            field=models.ForeignKey(blank=True, help_text='Optional page-specific partners row. If empty, site default is used.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.partnerrow'),
        ),
        migrations.CreateModel(
            name='PartnerRowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('custom_label', models.CharField(blank=True, help_text='Optional display label (defaults to partner name)', max_length=120)),
                ('link_override', models.URLField(blank=True, help_text='Optional custom URL (defaults to partner.website_url)')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portal.partner')),
                ('row', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.partnerrow')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortalSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_partner_row', models.ForeignKey(blank=True, help_text="Default partner row used on pages that don't choose one explicitly.", limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.partnerrow')),
                ('footer_partner_row', models.ForeignKey(blank=True, help_text='Optional compact partner row for near-footer placement.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.partnerrow')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
