# Generated by Django 5.2.8 on 2026-02-25 14:08

import django.db.models.deletion
import django.utils.timezone
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_partnerrow_partner_homepage_partner_row_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, default='footer', help_text='Where signup came from (e.g. footer, popup, page).', max_length=50)),
                ('status', models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed')], default='subscribed', max_length=20)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('site', models.ForeignKey(blank=True, help_text='Site where this signup was captured.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscribers', to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'verbose_name_plural': 'Newsletter subscribers',
                'ordering': ['-subscribed_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
