# Generated by Django 5.2.8 on 2026-02-25 15:06

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_newslettersubscriber'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_kicker', models.CharField(blank=True, default='About the hub', help_text='Small label above the hero title (e.g. About the hub).', max_length=80)),
                ('hero_title', models.CharField(default='SCACAF e-Hub for climate adaptation finance learning and collaboration', help_text='Main heading shown in the hero section.', max_length=180)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True, help_text='Intro paragraph below the hero title.')),
                ('vision_title', models.CharField(default='Vision', max_length=120)),
                ('vision_text', wagtail.fields.RichTextField(blank=True, help_text='Vision statement.')),
                ('mission_title', models.CharField(default='Mission', max_length=120)),
                ('mission_text', wagtail.fields.RichTextField(blank=True, help_text='Mission statement.')),
                ('objectives_title', models.CharField(blank=True, default='Objectives', max_length=120)),
                ('objectives_intro', wagtail.fields.RichTextField(blank=True)),
                ('audiences_title', models.CharField(blank=True, default='Who this hub is for', max_length=120)),
                ('audiences_intro', wagtail.fields.RichTextField(blank=True)),
                ('features_title', models.CharField(blank=True, default='What you can find in the hub', max_length=120)),
                ('features_intro', wagtail.fields.RichTextField(blank=True)),
                ('workflow_title', models.CharField(blank=True, default='How to use the hub', max_length=120)),
                ('workflow_intro', wagtail.fields.RichTextField(blank=True)),
                ('principles_title', models.CharField(blank=True, default='How we work', max_length=120)),
                ('principles_intro', wagtail.fields.RichTextField(blank=True)),
                ('cta_kicker', models.CharField(blank=True, default='Get involved', max_length=80)),
                ('cta_title', models.CharField(blank=True, default='Contribute, learn, and collaborate through the SCACAF e-Hub', max_length=160)),
                ('cta_text', wagtail.fields.RichTextField(blank=True, help_text='CTA supporting text.')),
                ('cta_button_label', models.CharField(blank=True, default='Contact us', max_length=60)),
                ('cta_button_url', models.URLField(blank=True, help_text='Optional external CTA button URL (used if no internal page is selected).')),
                ('cta_secondary_label', models.CharField(blank=True, default='', max_length=60)),
                ('cta_secondary_url', models.URLField(blank=True)),
                ('show_live_stats', models.BooleanField(default=True, help_text='If enabled, the template can show live counts (resources, webinars, experts, etc.).')),
                ('cta_button_page', models.ForeignKey(blank=True, help_text='Optional internal page link for CTA button (preferred over URL).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('cta_secondary_page', models.ForeignKey(blank=True, help_text='Optional internal secondary CTA link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'About page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_objectives', to='portal.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutFeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('book', 'Resources'), ('video', 'Webinars'), ('users', 'Expert directory'), ('message-square', 'Impact stories'), ('graduation-cap', 'Trainings'), ('search', 'Search / discovery'), ('layers', 'Collections'), ('sparkles', 'Featured content')], default='book', max_length=30)),
                ('link_url', models.URLField(blank=True, help_text='Optional external URL.')),
                ('link_label', models.CharField(blank=True, default='Explore', max_length=50)),
                ('link_page', models.ForeignKey(blank=True, help_text='Optional internal link for this feature card.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_features', to='portal.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutAudienceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('users', 'Users / community'), ('briefcase', 'Practitioners / implementers'), ('bank', 'Funders / institutions'), ('graduation-cap', 'Learners / training'), ('globe', 'Regional / global'), ('leaf', 'Climate / agriculture')], default='users', max_length=30)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_audiences', to='portal.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_principles', to='portal.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('step_title', models.CharField(max_length=140)),
                ('step_text', models.TextField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_workflow_steps', to='portal.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
