# Generated by Django 5.2.8 on 2026-02-25 19:09

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_aboutpage_aboutobjective_aboutfeaturecard_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_kicker', models.CharField(default='Contact', help_text='Small label above the page title', max_length=80)),
                ('hero_title', models.CharField(default='Get in touch with the SCACAF e-Hub team', max_length=220)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True, help_text='Short intro text shown below the title')),
                ('office_title', models.CharField(default='Contact information', max_length=120)),
                ('office_intro', wagtail.fields.RichTextField(blank=True, help_text='Optional short text above contact details')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=60)),
                ('office_address', wagtail.fields.RichTextField(blank=True)),
                ('office_hours', models.CharField(blank=True, help_text='e.g. Monday–Friday, 8:00 AM – 5:00 PM (EAT)', max_length=200)),
                ('map_embed_url', models.URLField(blank=True, help_text='Optional Google Maps embed URL')),
                ('form_title', models.CharField(default='Send us a message', max_length=120)),
                ('form_intro', wagtail.fields.RichTextField(blank=True, help_text='Optional text above the form')),
                ('submit_button_text', models.CharField(default='Send message', max_length=60)),
                ('privacy_note', models.CharField(blank=True, default='We’ll use your details only to respond to your message.', max_length=255)),
                ('success_title', models.CharField(default='Message sent', max_length=120)),
                ('success_message', wagtail.fields.RichTextField(blank=True, default='<p>Thank you for contacting us. We’ll get back to you as soon as possible.</p>')),
                ('notification_emails', models.TextField(blank=True, help_text='Comma-separated emails to notify (e.g. hub@org.org, support@org.org)')),
                ('send_auto_reply', models.BooleanField(default=True, help_text='Send a confirmation email to the person who submitted the form')),
                ('auto_reply_subject', models.CharField(blank=True, default='We received your message', max_length=200)),
                ('auto_reply_body', models.TextField(blank=True, default='Hello {name},\n\nThank you for contacting the SCACAF e-Hub team. We have received your message and will respond as soon as possible.\n\nBest regards,\nSCACAF e-Hub Team', help_text='You can use {name} in the message.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='portal.contactpage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
